---

- name: Update IPv4 CIDR and IPv6 prefix to random ranges
  command: "/usr/bin/vpn-server-api-update-ip --profile internet --host {{ \
  ansible_fqdn }}"
  args:
    creates: "config/config.php"

- name: Initialize CA
  command: "/usr/bin/vpn-server-api-init"
  become_user: www-data
  args:
    creates: "/usr/share/vpn-server-api/data/db.sqlite"

- name: Generate admin_pass
  set_fact:
    admin_pass: "{{ lookup('password', '/dev/null length=12') }}"
  when: admin_pass is not defined

- name: Generate guest_pass
  set_fact:
    guest_pass: "{{ lookup('password', '/dev/null length=12') }}"
  when: guest_pass is not defined

- name: Store admin_pass
  storefact:
      name: admin_pass
      value: "{{ admin_pass }}"
      path: "inventory/host_vars/{{ ansible_fqdn }}/accounts.yml"
  delegate_to: localhost
  become: false


- name: Store guest_pass
  storefact:
      name: guest_pass
      value: "{{ guest_pass }}"
      path: "inventory/host_vars/{{ ansible_fqdn }}/accounts.yml"
  delegate_to: localhost
  become: false
