---
- name: Generate admin_pass
  set_fact:
    admin_pass: "{{ lookup('password', '/dev/null length=12') }}"
  when: admin_pass is not defined

- name: Generate guest_pass
  set_fact:
    guest_pass: "{{ lookup('password', '/dev/null length=12') }}"
  when: guest_pass is not defined

- name: Store admin_pass
  storefact:
      name: admin_pass
      value: "{{ admin_pass }}"
      path: "inventory/host_vars/{{ ansible_fqdn }}/accounts.yml"
  delegate_to: localhost
  become: false

- name: Store guest_pass
  storefact:
      name: guest_pass
      value: "{{ guest_pass }}"
      path: "inventory/host_vars/{{ ansible_fqdn }}/accounts.yml"
  delegate_to: localhost
  become: false

- name: (re)create initial guest user
  shell: >-
      vpn-user-portal-add-user --user guest --pass "{{ guest_pass }}"

- name: (re)create initial admin user
  shell: >-
      vpn-user-portal-add-user --user admin --pass "{{ admin_pass }}"


