---

- name: firewall
  service:
    name: netfilter-persistent
    state: restarted

- name: openvpn
  service:
    name: openvpn
    state: restarted

- name: systemd
  systemd:
    daemon_reload: yes

- name: sysctl
  command: "sysctl --system"
