---

- name: firewall
  service:
    name: netfilter-persistent
    state: restarted

- name: openvpn
  command: "/usr/bin/apply_changes.sh"

- name: systemd
  systemd:
    daemon_reload: yes

- name: sysctl
  command: "sysctl --system"
