---
# Let's grab a letsencrypt cert
#
---

- name: Copy keys to host
  copy:
    src: "resources/SSL/{{ ansible_fqdn }}/{{ ansible_fqdn }}.key"
    dest: "{{ cert_location.key }}"

- name: Copy cert to host
  copy:
    src: "resources/SSL/{{ ansible_fqdn }}/{{ ansible_fqdn }}.crt"
    dest: "{{ cert_location.cert }}"
  notify: apache
